wrap_comments = true
format_doc_comments = true
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
format_macro_bodies = true
match_block_trailing_comma = true
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
match_arm_blocks = false
overflow_delimited_expr = true
edition = "2018"
